<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>name</key>
<string>Checklist</string>
<key>scopeName</key>
<string>text.clist</string>
<key>fileTypes</key>
<array>
<string>clist.txt</string>
</array>
<key>uuid</key>
<string>f104b009-0019-4ff5-81e9-47f81315a358</string>
<key>patterns</key>
<array>
<dict>
<key>match</key>
<string>#.*$</string>
<key>name</key>
<string>comment</string>
</dict>
<dict>
<key>match</key>
<string>"[^"]+"</string>
<key>name</key>
<string>string</string>
</dict>
<dict>
<key>match</key>
<string>sw_(?:checklist|continue|item(?:info|void)?|remark|rcolsize|show)</string>
<key>name</key>
<string>entity.name.tag</string>
</dict>
<dict>
<key>match</key>
<string>:|\|</string>
<key>name</key>
<string>punctuation.separator</string>
</dict>
<dict>
<key>match</key>
<string>(?&lt;=:|&&|\|\|)\(</string>
<key>name</key>
<string>punctuation.section.brackets.begin</string>
</dict>
<dict>
<key>match</key>
<string>\)(?=:|&&|\|\||$)</string>
<key>name</key>
<string>punctuation.section.brackets.end</string>
</dict>
<dict>
<key>match</key>
<string>&&|\|\|</string>
<key>name</key>
<string>keyword.operator.logical</string>
</dict>
<dict>
<key>match</key>
<string>(?&lt;=:)(\!|(?:\+|\-)?&gt;|&gt;?&lt;)?(\-?\d+|(\-?\d*\.\d+)?)(?=:|\)|$)</string>
<key>captures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>keyword.operator.logical</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>constant.numeric</string>
</dict>
</dict>
</dict>
<dict>
<key>match</key>
<string>(?&lt;=:|\()\w+(?:\/\w+)+(?:(\[)(\d+)(\]))?(?=:)</string>
<key>name</key>
<string>entity.name.namespace</string>
<key>captures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>punctuation.section.brackets.begin</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>constant.numeric.integer</string>
</dict>
<key>3</key>
<dict>
<key>name</key>
<string>punctuation.section.brackets.end</string>
</dict>
</dict>
</dict>
<dict>
<key>match</key>
<string>.</string>
<key>name</key>
<string>string</string>
</dict>
</array>
</dict>
</plist>
